### PR TITLE
Support for ManyToManyField in ClusterableModel.

### PR DESCRIPTION
**Pull request by theju**
Please have a look at this PR and let me know your thoughts.

### CODE REVIEW

**Comment by theju** [comment]
Refs #3. Tests fail for django v1.6 and I am not sure we should care now that it is unsupported. The tests fail for django v1.7 (AttributeError: 'RelatedObject' object has no attribute 'related_model') probably because I am using the new meta public api.

**Comment by kaedroho** [comment]
The issue with ``related_model`` could be solved by using this function: https://github.com/torchbox/django-modelcluster/blob/master/modelcluster/models.py#L16-L23

**Comment by theju** [comment]
@kaedroho Thanks. I used that function and fixed that issue but running into more issues with django 1.7 model meta api. I next applied this patch:

```
diff --git a/modelcluster/models.py b/modelcluster/models.py
index 39a2f3a..b379ddf 100644
--- a/modelcluster/models.py
+++ b/modelcluster/models.py
@@ -5,7 +5,7 @@ import datetime
 
 import django
 from django.db import models
-from django.db.models.fields.related import ForeignObjectRel
+from django.db.models.fields.related import ForeignObjectRel, ManyToManyField
 from django.db.models.fields import FieldDoesNotExist
 from django.utils.encoding import is_protected_type
 from django.core.serializers.json import DjangoJSONEncoder
@@ -156,7 +156,10 @@ class ClusterableModel(models.Model):
         via kwargs
         """
         child_relation_names = [rel.get_accessor_name() for rel in get_all_child_relations(self)]
-        child_relation_names += [ii.name for ii in self._meta.get_fields() if ii.many_to_many == True]
+        if django.VERSION >= (1, 8):
+            child_relation_names += [ii.name for ii in self._meta.get_fields() if ii.many_to_many == True]
+        else:
+            child_relation_names += [ii.name for ii in self._meta.fields if isinstance(ii, ManyToManyField) == True]
 
         is_passing_child_relations = False
         for rel_name in child_relation_names:
@@ -182,7 +185,10 @@ class ClusterableModel(models.Model):
         Save the model and commit all child relations.
         """
         child_relation_names = [rel.get_accessor_name() for rel in get_all_child_relations(self)]
-        child_relation_names += [ii.name for ii in self._meta.get_fields() if ii.many_to_many == True]
+        if django.VERSION >= (1, 8):
+            child_relation_names += [ii.name for ii in self._meta.get_fields() if ii.many_to_many == True]
+        else:
+            child_relation_names += [ii.name for ii in self._meta.fields if isinstance(ii, ManyToManyField) == True]
 
         update_fields = kwargs.pop('update_fields', None)
         if update_fields is None:
```

but run into the following error with django 1.7:

```
======================================================================
ERROR: test_m2m_field (tests.tests.test_cluster.ClusterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/theju/django-modelcluster/tests/tests/test_cluster.py", line 213, in test_m2m_field
    article.authors = [author_1, author_2]
  File "/home/theju/django-modelcluster/modelcluster/fields.py", line 478, in __set__
    manager = self.__get__(instance)
  File "/home/theju/django-modelcluster/modelcluster/fields.py", line 465, in __get__
    return self.related_m2m_manager_cls(
  File "/home/theju/dj17_env/lib/python3.4/site-packages/django/utils/functional.py", line 55, in __get__
    res = instance.__dict__[self.func.__name__] = self.func(instance)
  File "/home/theju/django-modelcluster/modelcluster/fields.py", line 458, in related_m2m_manager_cls
    self.related_manager_cls
  File "/home/theju/django-modelcluster/modelcluster/fields.py", line 261, in create_deferring_many_related_manager
    relation_name = related.get_accessor_name()
AttributeError: 'ManyToManyRel' object has no attribute 'get_accessor_name'
```

**Comment by theju** [comment]
Django 1.7's meta API is really difficult for me to comprehend. I am glad that the django devs refactored the code for 1.8 and made it public and that I am starting a new project on django 1.8 :smiley: Sorry but I don't think I have the time or patience to get the backwards compatibility patch done.

**Pull request closed without merging**
